"""add dry_run to outbox_events

Revision ID: ccfbf28b01da
Revises: acd9a6926f3b
Create Date: 2026-09-16 13:25:01.206950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfbf28b01da'
down_revision: Union[str, Sequence[str], None] = 'acd9a6926f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so this doesn't fail against a table that already has rows — the
    # autogenerated version omitted it, which would reject a NOT NULL add on non-empty
    # outbox_events. True is also the safe default direction if an old event is ever
    # somehow reprocessed without one.
    op.add_column(
        'outbox_events',
        sa.Column('dry_run', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'dry_run')
    # ### end Alembic commands ###
