"""add ceo_commands table

Revision ID: e7cf4f9229a5
Revises: 374291fd0fdf
Create Date: 2026-09-16 06:05:25.881812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7cf4f9229a5'
down_revision: Union[str, Sequence[str], None] = '374291fd0fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ceo_commands',
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('intent', sa.Enum('find_opportunities', 'find_leads', 'start_campaign', 'pause_campaign', 'resume_campaign', 'kill_campaign', 'show_decisions', 'show_status', 'engage_kill_switch', 'release_kill_switch', 'unknown', name='commandintent', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'answered', 'executed', 'blocked', 'unrecognized', 'failed', name='commandstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ceo_commands'))
    )
    op.create_index(op.f('ix_ceo_commands_created_at'), 'ceo_commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_ceo_commands_status'), 'ceo_commands', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ceo_commands_status'), table_name='ceo_commands')
    op.drop_index(op.f('ix_ceo_commands_created_at'), table_name='ceo_commands')
    op.drop_table('ceo_commands')
    # ### end Alembic commands ###
