"""add proposal_id to messages and unique lead_id on deals

Revision ID: ed1b7c78bb3c
Revises: ccfbf28b01da
Create Date: 2026-09-16 15:13:19.540366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1b7c78bb3c'
down_revision: Union[str, Sequence[str], None] = 'ccfbf28b01da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_deals_lead', 'deals', ['lead_id'])
    op.add_column('messages', sa.Column('proposal_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_messages_proposal_id'), 'messages', ['proposal_id'], unique=False)
    op.create_foreign_key(op.f('fk_messages_proposal_id_proposals'), 'messages', 'proposals', ['proposal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_proposal_id_proposals'), 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_proposal_id'), table_name='messages')
    op.drop_column('messages', 'proposal_id')
    op.drop_constraint('uq_deals_lead', 'deals', type_='unique')
    # ### end Alembic commands ###
